#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import urllib.request, json

city = "Grayslake"
api_key = "8fdd084cefbd9dae1b655b7892548350" 

weather = eval(str(urllib.request.urlopen("http://api.openweathermap.org/data/2.5/weather?q={}&APPID={}".format(city, api_key)).read())[2:-1])

info = weather["weather"][0]["description"].capitalize()
temp = int(float(weather["main"]["temp"]) - 272.15)

print("%s, %i °C" % (info, temp))
